Fix building with Ogre 1.12
stuntrally/stuntrally pull request #37
Opened 2021-10-23 16:41 UTC by etam

I don't know if it's compatible with earlier Ogre versions.

2021-11-11 00:55 UTC, paroj requested changes

2021-11-11 00:55 UTC, paroj commented on CMakeLists.txt
> +        include_directories(${OGRE_INCLUDE_DIRS} ${OGRE_Terrain_INCLUDE_DIRS} ${OGRE_Paging_INCLUDE_DIRS} ${OGRE_Overlay_INCLUDE_DIRS} ${OGRE_Bites_INCLUDE_DIRS})
these cmake changes are unnecessary, if Ogre 1.12 is properly installed, it should be taking the branch above.

2022-01-28 22:14 UTC, cryham commented
So @paroj is this needed if Ogre 1.13 support is merged now?

2022-01-29 14:19 UTC, paroj commented
as far as I can see, it was not needed before either

2022-01-29 15:03 UTC, cryham commented
Okay then, I will close this. If needed feel free to reopen.

2022-01-29 15:03 UTC, closed without merging